### ISSUE TITLE
Conflict with uniLinks

### ISSUE THREAD

**Issue by vizakenjack** [ben-xD/push#28]
Thanks for your package! I used flutter_apns and tried to migrate to Push. It works fine, but I got one annoying issue.

I use uni_links with this code to start the app with an initial link:

```
final initialUri = await getInitialUri();
openUri(initialUri);
```

It works fine when I use flutter_apns, but it stops working right after I add Push to pubspec.yaml.
Please note that it only affects the initial start, when the app was terminated. 

Is there any ideas how can I fix it?

I also tried https://pub.dev/packages/app_links instead of uni_links, but still was not able to get initial url.

**Comment by kaiquegazola** [comment]
It also happens with my app using firebase_dynamic_links on iOS. It doesn't seem to happen on Android for me.

In my investigation, it appears that the issue is related to returning false in the delegate didFinishLaunchingWithOptions. When returning true, everything seems to work normally.

https://github.com/ben-xD/push/blob/0b0ce07c268a5b487a4cd784443abd86eb834e92/push_ios/ios/Classes/SwiftPushPlugin.swift#L21-L30C6

**Comment by nikolaydimitrov** [comment]
@kaiquegazola is correct, I had to fork and change that return statement, and do this in `pubspec.yaml` to work around it:
```
dependency_overrides:
  push_ios:
    git:
      url: https://github.com/circled-me/push-plugin.git
      ref: 9d2bf81
      path: push_ios
```
